baseURL = "https://rafalmaleska.github.com/certs/"
languageCode = "en-us"
title = "certs"
theme = "slate"

publishDir = "public"

[ params ]
Favicon = "favicon.ico"
OpenLinksInNewWindow = true

[[ params.nav ]]
name = "kafka"
tag = "kafka"
icon = "server"

[[ params.nav ]]
name = "search"
tag = "search"
icon = "search"

[[ params.nav ]]
name = "shopping"
tag = "shopping"
icon = "shopping-basket"

[[ params.nav ]]
name = "music"
tag = "music"
icon = "headphones"

[[ params.nav ]]
name = "video"
tag = "video"
icon = "video-camera"
