baseURL = "https://rafalmaleska.github.io/"
languageCode = "en-us"
title = "Rafał"
theme = "minimal"
disqusShortname = "Rafał" # delete this to disable disqus comments
googleAnalytics = "UA-88635181-1"

[params]
    author = "Calin Tataru"
    description = "Małeska-Manhart"
    githubUsername = "#rafalmaleska"
    accent = "Fuchsia"
    showBorder = true
    backgroundColor = "LawnGreen"
    font = "Playfair Display" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    copyright=" "

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:r.maleska@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/rafalmaleska/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/rafalmaleska/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/rafalmaleska/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "http://instagram.com/ohrafal"
    name = "instagram"
    weight = 5

[[menu.icon]]
    url = "https://facebook.com/Rafal.Maleska"
    name = "facebook"
    weight = 6